 // example: mySANSANDAREP(0).mySSVDAREP()->Init({mySSVDAREP0,mySSVDAREP1});
 SANDAREP::BUS_SAN::rep(2).P()->Init({PDRSVDAREP2});
 // example: mySANSANDAREP(0).mySSVDAREP()->Init({mySSVDAREP0,mySSVDAREP1});
 SANDAREP::BUS_SAN::rep(2).Q()->Init({QDRSVDAREP2});
 // example: mySANSANDAREP(0).mySSVDAREP()->Init({mySSVDAREP0,mySSVDAREP1});
 SANDAREP::BUS_SAN::rep(2).V()->Init({VDRSVDAREP2});
 // example: mySANSANDAREP(0).mySSVDAREP()->Init({mySSVDAREP0,mySSVDAREP1});
 SANDAREP::BUS_SAN::rep(2).Delta()->Init({DeltaDRSVDAREP2});
 // example: mySANSANDAREP(0).mySSVDAREP()->Init({mySSVDAREP0,mySSVDAREP1});
 SANDAREP::BUS_SAN::rep(2).BusStatus()->Init({BusStatusDRSVDAREP2});
 // example: mySANSANDAREP(0).mySSVDAREP()->Init({mySSVDAREP0,mySSVDAREP1});
 SANDAREP::BUS_SAN::rep(2).BranchStatus()->Init({BranchStatusDRSVDAREP3, BranchStatusDRSVDAREP7, BranchStatusDRSVDAREP8});
